### ISSUE TITLE
Report of cg analyzer

### ISSUE THREAD

**Issue by bharathbiju** [bharathbiju/myapp#14]

**Comment by Samson-Antony** [comment]
refer image sent by me for reference.. the graph there is not necessary but appreciated. if any better ideas arises it cam also be implemented.

extra interest based results also to be added for eg. suggesting him/her to apply civil service with BMI calculation.. [enhancement]

**Comment by Samson-Antony** [comment]
![WhatsApp Image 2020-03-29 at 12 26 31 PM](https://user-images.githubusercontent.com/49990770/77954687-ab4cb200-72ec-11ea-857f-24b530c1b5d5.jpeg)

**Comment by bharathbiju** [comment]
@Samson-Antony  for each course we will have separate collage list , you diagram does not specify which collage is best for which course , don't you think that is a problem ?

**Comment by Samson-Antony** [comment]
just an outlook for the display da. we should correct it..
 like buttons for the courses.. when clicked.. it goes to the clg list
